# Generated by Django 3.0.5 on 2020-04-27 11:23

from django.db import migrations, models
import django.db.models.deletion
import jass.models


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', jass.models.CardField()),
                ('played', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jass.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jass.Player')),
            ],
            options={
                'unique_together': {('card', 'game')},
            },
        ),
    ]
