# Generated by Django 3.0.5 on 2020-04-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0005_trick'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='trick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jass.Trick'),
        ),
    ]
