# Generated by Django 3.0.5 on 2020-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0006_playingcard_trick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
