# Generated by Django 3.0.5 on 2020-05-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0009_game_trumps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trumps',
            field=models.CharField(choices=[('spade', 'Spade'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('club', 'Club')], max_length=7),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.BooleanField()),
                ('suit', models.CharField(choices=[('spade', 'Spade'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('club', 'Club')], max_length=7)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jass.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jass.Player')),
            ],
        ),
    ]
