# Generated by Django 3.0.5 on 2020-05-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0010_auto_20200502_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='order_in_trick',
            field=models.SmallIntegerField(null=True),
        ),
    ]
