# Generated by Django 3.0.5 on 2020-07-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0012_seriesplayer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesplayer',
            unique_together={('series', 'position')},
        ),
    ]
