# Generated by Django 3.0.5 on 2021-04-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0015_auto_20200708_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seriesplayer',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jass.Series'),
        ),
    ]
