# Generated by Django 3.0.5 on 2022-04-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0016_auto_20210405_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='jass.Series'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jass.Game'),
        ),
        migrations.AlterField(
            model_name='playingcard',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='jass.Game'),
        ),
        migrations.AlterField(
            model_name='playingcard',
            name='trick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='jass.Trick'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='jass.Game'),
        ),
    ]
