# Generated by Django 3.0.5 on 2022-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jass', '0017_auto_20220407_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='points2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(null=True),
        ),
    ]
